#!/usr/bin/env python
# -*- coding: utf-8 -*-
import signal
import sys
import time

#from docopt import docopt
from augure.Augure import Daemon

if __name__ == '__main__':
    augure = Daemon()
    augure.run()