#!/usr/bin/env python
# -*- coding: utf-8 -*-
import signal
import sys
import time

#from docopt import docopt
from augure import Worker

if __name__ == '__main__':

    daemon = Worker('/tmp/augure.pid')

    if len(sys.argv) == 2:
        if 'start' == sys.argv[1]:
            daemon.start()
        elif 'stop' == sys.argv[1]:
            daemon.stop()
        elif 'restart' == sys.argv[1]:
            daemon.restart()
        elif 'status' == sys.argv[1]:
            daemon.status()
        else:
            print("Unknown command")
            sys.exit(2)
        sys.exit(0)
    else:
        print("usage: %s start|stop|restart|status")
        sys.exit(2)
